// Boot-time consent-text drift guard.
//
// Verifies that the SHA-256 of CONSENT_TEXT matches the committed
// CONSENT_TEXT_SHA256 constant. Any drift means consent-text.ts was edited
// without re-running `pnpm --filter @humyn/api run legal:hash` — the hash
// committed alongside the text is now stale, and counsel's sign-off on the
// committed text is no longer mechanically tied to what users see at sign-in.
//
// `verifyConsentTextHash()` is invoked at the start of `buildApp()` (apps/api/src/app.ts)
// before any plugin or route registration. Mismatch throws ConsentTextDriftError
// → API refuses to listen → CI / deploy / test all fail loudly.
//
// W7 follow-through: consent-text-hash.ts is now a deterministic build artifact
// regenerated by scripts/legal-hash.ts. Boot guard enforces the invariant; the
// legal-hash regen script enforces the freshness.

import { createHash } from 'node:crypto';
import { CONSENT_TEXT } from './consent-text.js';
import { CONSENT_TEXT_SHA256 } from './consent-text-hash.js';

export class ConsentTextDriftError extends Error {
  constructor(actual: string, expected: string) {
    super(
      `Consent text drift: on-disk SHA-256 = ${actual}; committed CONSENT_TEXT_SHA256 = ${expected}. ` +
        `Refusing to start the API. Run \`pnpm --filter @humyn/api run legal:hash\` and update ` +
        `consent-text-hash.ts (with counsel sign-off) to resolve.`,
    );
    this.name = 'ConsentTextDriftError';
  }
}

export function verifyConsentTextHash(): void {
  const actual = createHash('sha256').update(CONSENT_TEXT).digest('hex');
  if (actual !== CONSENT_TEXT_SHA256) {
    throw new ConsentTextDriftError(actual, CONSENT_TEXT_SHA256);
  }
}
